name: Export Plane Images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull all images
        run: |
          docker pull makeplane/plane-frontend:stable
          docker pull makeplane/plane-api:stable
          docker pull makeplane/plane-worker:stable
          docker pull makeplane/plane-proxy:stable
          docker pull postgres:15
          docker pull redis:7
          docker pull minio/minio:latest

      - name: Save to tar file
        run: |
          docker save -o plane-offline-images.tar \
            makeplane/plane-frontend:stable \
            makeplane/plane-api:stable \
            makeplane/plane-worker:stable \
            makeplane/plane-proxy:stable \
            postgres:15 redis:7 minio/minio:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plane-offline-images
          path: plane-offline-images.tar
          retention-days: 7
